### ISSUE TITLE
Tap issue 

### ISSUE THREAD

**Issue by iRunner** [hashgraph/homebrew-tap#1]
Running `brew tap hashgraph/tap` 

Gives me this: 

```==> Tapping hashgraph/tap
Cloning into '/usr/local/Homebrew/Library/Taps/hashgraph/homebrew-tap'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/hashgraph/homebrew-tap/sha256update.rb
No such file or directory @ rb_sysopen - ../hash.txt
Error: Cannot tap hashgraph/tap: invalid syntax in tap!
```

I'm not exactly sure what these files are: 

https://github.com/hashgraph/homebrew-tap/blame/master/sha256update.rb#L17-L19

**Comment by calvinchengx** [comment]
@iRunner 

my apologies, the `sha256update.rb` script that I added wasn't placed in the right directory, so it got treated as a homebrew formula. It isn't a homebrew formula.

Fixed and closed via commit #9997ee50e90ed61aa0ec95d2b145388142938959
